name: iOS starter workflow

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ feature/GitHub_Actions ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with: 
          fetch-depth: 0
          clean: true
          submodules: true
          lfs: false
      
      #- name: Initialize
       # shell: sh
        #run: |
         #    pwd
          #   rm -rf Source/results/*
           #  rm -rf Source/build/*.ipa
            # rm -rf ~/Library/Developer/Xcode/DerivedData
             #rm -rf Source/DerivedData
             #./ci-build-support/update_version.sh
             #rm -rf ./Source/Library/Podfile.lock
             #echo "Running pod install for ${podfilePath}"
             #cd ./Source/Library && pod cache clean --all && pod repo update && pod install
             
      # extract branch name
      #- name: Extract branch name
      #  if: github.event_name != 'pull_request'
      #  shell: bash
      #  run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
      #  id: extract_branch
      
      - name: Zip Components
        if: startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release/platform_')
        shell: bash
        run: |
             PODSPEC_PATH="ci-build-support/Versions.rb"
             VERSION_REGEX="VersionCSWPlatform[^'|\\"]*['|\\"]([^'|\\"]*)['|\\"]"
             COMPONENT_VERSION=cat $PODSPEC_PATH | egrep -o $VERSION_REGEX | sed -E s/$VERSION_REGEX/\\1/
             COMMIT_HASH=git rev-parse HEAD
